Make NumPy available:

In [2]:
import numpy as np

## Exercise 07.1 (indexing and timing)

Create two very long NumPy arrays `x` and `y` and sum the arrays using:

1. The NumPy addition syntax, `z = x + y`; and
2. A `for` loop that computes the sum entry-by-entry

Compare the time required for the two approaches for vectors of different lengths (use a very long vector for 
the timing). The values of the array entries are not important for this test. Use `%time` to report the time.

*Hint:* To loop over an array using indices, try a construction like:

In [3]:
x = np.ones(10)
y = np.ones(len(x))
for i in range(len(x)):
    print(x[i]*y[i])

print(x)
print(y)

1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### (1) Add two vectors using built-in addition operator:

In [13]:
import numpy as np
x = np.random.rand(1000)
y = np.random.rand(1000)
z = x + y

%time norm = x + y

print(x)
print(y)
print(z)

CPU times: user 16 µs, sys: 0 ns, total: 16 µs
Wall time: 19.3 µs
[0.90952978 0.98760229 0.19185822 0.52458336 0.16737875 0.92690673
 0.46347148 0.68500619 0.33714591 0.411655   0.03989874 0.48390178
 0.43349908 0.35426257 0.93852722 0.72494433 0.63336274 0.54002058
 0.95486426 0.30973444 0.53066976 0.53115683 0.55312596 0.88112291
 0.99998827 0.26813575 0.10971082 0.59724566 0.34640409 0.25376162
 0.52234942 0.71477577 0.43243164 0.23708925 0.77143433 0.7270469
 0.84113714 0.91662229 0.27413737 0.67280019 0.62588973 0.62060563
 0.99940421 0.02268207 0.98571681 0.9818335  0.58569576 0.83629902
 0.20504604 0.6537945  0.72619347 0.3132625  0.76378381 0.32214531
 0.72961477 0.21896225 0.18084908 0.08868971 0.96822901 0.51019778
 0.97235443 0.32047818 0.64202906 0.3793661  0.65549166 0.03473999
 0.26799841 0.18601434 0.35739588 0.94532232 0.7426211  0.13997029
 0.9034059  0.84887628 0.96171275 0.69992373 0.71549636 0.65331491
 0.76961087 0.48372465 0.20556543 0.29340118 0.85531472 0.430965

#### (2) Add two vectors using own implementation:

In [12]:
import numpy as np
x = np.random.rand(1000)
y = np.random.rand(1000)

def addition():
  z = []
  for i in range(len(x)):
    z.append(x[i]+y[i])
  res = np.array(z)
  return res

%time norm = addition()

print(x)
print(y)
print(addition())

CPU times: user 640 µs, sys: 0 ns, total: 640 µs
Wall time: 643 µs
[1.38246105e-01 7.71530283e-01 7.05614980e-01 2.61122261e-01
 8.75537869e-01 1.06371440e-01 8.80412907e-01 6.11022071e-02
 8.12170447e-01 9.04031328e-01 4.55587865e-01 2.00082444e-01
 3.74922149e-01 2.88045355e-01 4.00698683e-02 5.05350749e-01
 9.61111406e-01 9.21879456e-02 4.79881870e-01 9.51532928e-01
 9.64888210e-01 5.34205194e-01 8.63473299e-01 1.88555475e-01
 2.09084201e-02 3.04158559e-01 1.38346950e-01 5.38172137e-01
 8.06723513e-01 6.93599736e-01 9.92970137e-01 3.20035266e-03
 7.69952309e-01 2.85666729e-01 3.04371646e-01 2.23927838e-02
 2.83242176e-01 5.68116916e-02 9.20479282e-02 7.43008825e-01
 7.78075989e-01 4.57294104e-01 7.06470194e-01 3.06869094e-01
 3.17269164e-01 1.95110298e-01 1.56089499e-01 9.79899968e-01
 4.95405894e-02 4.30537870e-01 2.20372646e-01 8.40889215e-01
 3.68502754e-01 5.38844460e-01 7.85610494e-02 9.48398162e-01
 8.59038093e-01 6.53671435e-01 5.28115518e-01 1.28924633e-01
 9.77831118e-01 9.

### Optional extension: just-in-time (JIT) compilation

You will see a large difference in the time required between your NumPy and 'plain' Python implementations. This is due to Python being an *interpreted* language as opposed to a *compiled* language. A way to speed up plain Python implementions is to convert the interpreted Python code into compiled code. A tool for doing this is [Numba](https://numba.pydata.org/).

Below is an example using Numba and JIT to accelerate a computation:

In [ ]:
!pip -q install numba 
import numba
import math

def compute_sine_native(x):
    z = np.zeros(len(x))
    for i in range(len(z)):
        z[i] = math.sin(x[i])
    return z

@numba.jit
def compute_sine_jit(x):
    z = np.zeros(len(x))
    for i in range(len(z)):
        z[i] = math.sin(x[i])
    return z
    
x = np.ones(10000000)
%time z = compute_sine_native(x)
compute_sine_jit(x)
%time z = compute_sine_jit(x)

**Task:** Test if Numba can be used to accelerate your implementation that uses indexing to sum two arrays, and by how much.

## Exercise 07.2 (member functions and slicing)

Anonymised scores (out of 60) for an examination are stored in a NumPy array. Write:

1. A function that takes a NumPy array of the raw scores and returns the scores as percentages, sorted from 
   lowest to highest (try using `scores.sort()`, where `scores` is a NumPy array holding the scores).
1. A function that returns the maximum, minimum and mean of the raw scores as a dictionary with the 
   keys '`min`', '`max`' and '`mean`'. Use the NumPy array functions `min()`, `max()` and `mean()` to do the 
   computation, e.g. `max = scores.max()`.  
   
   Design your function for the min, max and mean to optionally exclude the highest and lowest scores from the 
   computation of the min, max and mean. 
   
   *Hint:* sort the array of scores and use array slicing to exclude
   the first and the last entries.

Use the scores 
```python
scores = np.array([58.0, 35.0, 24.0, 42, 7.8])
```
to test your functions.

In [ ]:
scores = np.array([58.0, 35.0, 24.0, 42, 7.8])

def to_percentage_and_sort(scores):
    per = scores/60*100
    per.sort()
    return per

def statistics(scores, exclude=False):
    scores.sort()
    if exclude == False:
      #don't exclude highest and lowest
      max = scores.max()
      min = scores.min()
      mean = scores.mean()
      dict = {'max':max,'min':min,'mean':mean}
      return dict
    else:
      #exclude highest and lowest
      max = scores[1:-1].max()
      min = scores[1:-1].min()
      mean = scores[1:-1].mean()
      dict = {'max':max,'min':min,'mean':mean}
      return dict

In [ ]:
scores = np.array([58.0, 35.0, 24.0, 42, 7.8])
assert np.isclose(to_percentage_and_sort(scores), [ 13.0, 40.0, 58.33333333,  70.0, 96.66666667]).all()

s0 = statistics(scores)
assert round(s0["min"] - 7.8, 10) == 0.0
assert round(s0["mean"] - 33.36, 10) == 0.0
assert round(s0["max"] - 58.0, 10) == 0.0

s1 = statistics(scores, True)
assert round(s1["min"] - 24.0, 10) == 0.0
assert round(s1["mean"] - 33.666666666666666667, 10) == 0.0
assert round(s1["max"] - 42.0, 10) == 0.0

## Exercise 07.3 (slicing)

For the two-dimensional array

In [ ]:
A = np.array([[4.0, 7.0, -2.43, 67.1],
             [-4.0, 64.0, 54.7, -3.33],
             [2.43, 23.2, 3.64, 4.11],
             [1.2, 2.5, -113.2, 323.22]])
print(A)

[[   4.      7.     -2.43   67.1 ]
 [  -4.     64.     54.7    -3.33]
 [   2.43   23.2     3.64    4.11]
 [   1.2     2.5  -113.2   323.22]]


use array slicing for the below operations, printing the results to the screen to check. Try to use array slicing such that your code would still work if the dimensions of `A` were enlarged.



#### 1. Extract the third column as a 1D array

In [ ]:
A = np.array([[4.0, 7.0, -2.43, 67.1],
             [-4.0, 64.0, 54.7, -3.33],
             [2.43, 23.2, 3.64, 4.11],
             [1.2, 2.5, -113.2, 323.22]])
third_col = A[:,2]

print(A)
print(third_col)

[[   4.      7.     -2.43   67.1 ]
 [  -4.     64.     54.7    -3.33]
 [   2.43   23.2     3.64    4.11]
 [   1.2     2.5  -113.2   323.22]]
[  -2.43   54.7     3.64 -113.2 ]


#### 2. Extract the first two rows as a 2D sub-array

In [ ]:
A = np.array([[4.0, 7.0, -2.43, 67.1],
             [-4.0, 64.0, 54.7, -3.33],
             [2.43, 23.2, 3.64, 4.11],
             [1.2, 2.5, -113.2, 323.22]])
first_2_rows = A[:2]
print(first_2_rows)

[[ 4.    7.   -2.43 67.1 ]
 [-4.   64.   54.7  -3.33]]


#### 3.  Extract the bottom-right $2 \times 2$ block as a 2D sub-array

In [ ]:
A = np.array([[4.0, 7.0, -2.43, 67.1],
             [-4.0, 64.0, 54.7, -3.33],
             [2.43, 23.2, 3.64, 4.11],
             [1.2, 2.5, -113.2, 323.22]])
bot_right_2x2 = A[2:,2:]

print(bot_right_2x2)

[[   3.64    4.11]
 [-113.2   323.22]]


#### 4. Sum the last column

In [ ]:
A = np.array([[4.0, 7.0, -2.43, 67.1],
             [-4.0, 64.0, 54.7, -3.33],
             [2.43, 23.2, 3.64, 4.11],
             [1.2, 2.5, -113.2, 323.22]])
sum = A[:,-1].sum()
print(sum)

391.1


#### Compute transpose

Compute the transpose of `A` (search online to find the function/syntax to do this).

In [ ]:
A = np.array([[4.0, 7.0, -2.43, 67.1],
             [-4.0, 64.0, 54.7, -3.33],
             [2.43, 23.2, 3.64, 4.11],
             [1.2, 2.5, -113.2, 323.22]])
transpose = A.transpose()

print(transpose)

[[   4.     -4.      2.43    1.2 ]
 [   7.     64.     23.2     2.5 ]
 [  -2.43   54.7     3.64 -113.2 ]
 [  67.1    -3.33    4.11  323.22]]


## Exercise 07.4 (optional extension)

In a previous exercise you implemented the bisection algorithm to find approximate roots of a mathematical function. Use the SciPy bisection function `optimize.bisect` (https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.bisect.html) to find roots of the mathematical function that was used in the previous exercise. Compare the results computed by SciPy and your program from the earlier exercise, and compare the computational time (using `%time`).

In [ ]:
from scipy import optimize

# YOUR CODE HERE
raise NotImplementedError()